# Generated by Django 4.2.6 on 2023-10-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
