# Generated by Django 4.2.6 on 2023-10-25 14:54

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('main', '0004_customtag_customtaggeditem_alter_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtaggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customtaggeditem',
            name='tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='CustomTag',
        ),
        migrations.DeleteModel(
            name='CustomTaggedItem',
        ),
    ]
